import Vue from 'vue';
import Unicon from 'vue-unicons';
import {
  uniShareAlt,
  uniLabelAlt,
  uniHomeAlt,
  uniStarMonochrome,
  uniClipboardNotes,
  uniNotes,
  uniArrowLeft,
  uniArrowUpRight,
  uniFilter,
  uniPlus,
  uniStar,
  uniApps,
  uniTrash,
  uniSearch,
  uniAngleDown,
  uniPen,
  uniMultiply,
  uniCheck,
  uniGripHorizontalLine,
  uniEllipsisH,
  uniGlobe,
  uniWindow,
  uniAngleLeft,
} from 'vue-unicons/src/icons';

Unicon.add([
  uniShareAlt,
  uniLabelAlt,
  uniHomeAlt,
  uniStarMonochrome,
  uniClipboardNotes,
  uniNotes,
  uniArrowLeft,
  uniArrowUpRight,
  uniFilter,
  uniPlus,
  uniStar,
  uniApps,
  uniTrash,
  uniSearch,
  uniAngleDown,
  uniPen,
  uniMultiply,
  uniCheck,
  uniGripHorizontalLine,
  uniEllipsisH,
  uniGlobe,
  uniWindow,
  uniAngleLeft,
]);
Vue.use(Unicon);
